main: com.rayzr522.chunkfixer.ChunkFixer
name: ChunkFixer
version: 1.0.0
description: Fixes a problem with loaded chunks.
author: Rayzr
commands:
  fixworld:
    description: Fixes a world
    usage: "\u00A7CUsage: /fixworld <world>"
    permission: ChunkFixer.main
